### PR TITLE
Package.json Updates

### PR DESCRIPTION
**Pull request by ssimontis**
Originally just wanted to hit #622 before I realized we had over 30k vulnerabilities in our dependencies. I went ahead and updated packages to fix that so we are (at least at the time of this message) vulnerability-free!
# Pull Request Template

The code review checklist below is used for all pull requests.

 1. Review the list before submitting your pull request.
 2. Leave the list intact for the code reviewer's use.

## Checklist

- [X] Latest code from master has been merged into the pull request branch
- [X] Honors [the seven code virtues](https://pragprog.com/magazines/2011-08/how-virtuous-is-your-code)
  - [X] Working, as opposed to incomplete
  - [X] Unique, as opposed to duplicated
  - [X] Simple, as opposed to complicated
  - [X] Clear, as opposed to puzzling
  - [X] Easy, as opposed to difficult
  - [X] Developed, as opposed to primitive
  - [X] Brief, as opposed to chatty
- [X] Code is camelCased
- [X] No commented out code (if required, place // TODO above with explanation)
- [X] No linting issues
- [X] Automated tests exist and pass
- [X] Build is successful (`npm run build`)
- [X] Works in IE 11, Chrome, Firefox, and Edge

## Thanks!

:heart:

Some of these could probably use a lot more testing. Specifically the last item. Someone with a complex project would be able to better confirm that the package upgrades didn't affect anything.

_Edited by @kwelch: fixed checkboxes_

### CODE REVIEW

**Comment by kwelch** [comment]
All of the updates within range? (except browsersync) I am surprised for the number of lock changes to the number of package changes.

**Comment by ssimontis** [comment]
@kwelch You are correct, I was quite surprised too. When I saw the vulnerability number, I was expecting NPM to rearrange everything inside of the app, but it looks like BrowserSync was able to shed many dependencies which were responsible for a disproportionate number of major vulnerabilities.

**Comment by nickytonline** [comment]
If all builds fine,I don't see any reason why we can't merge this. Thanks for taking a peek at this @ssimontis.

**Comment by nickytonline** [comment]
This also fixes #622.

**Comment by kwelch** [comment]
That should hopefully also trigger appveyor to rebuild, so the merge button activates.

**Comment by ssimontis** [comment]
Sorry, didn't see your request last night. It is done now!

**Comment by kwelch** [comment]
Looks like the build passed in appveyor, but it didn't report back. 
https://ci.appveyor.com/project/CoryHouse/react-slingshot/builds/26397208

We may need @coryhouse to look into that.

**Comment by coryhouse** [comment]
I'm gonna assume that Appveyor lack of report back was just a fluke. Build passed there anyway, so merging. Thanks for the PR! :)

**Comment by ssimontis** [comment]
@coryhouse Check out this maybe you need to hit up the Github API directly in the build? https://gist.github.com/IlyaFinkelshteyn/def2394231afb7f06dcaeaceda1fb1ae I wasn't sure if you kept it like this so you got final admin approval of all PRs, so I didn't set it up (would have needed you for the keys anyways).

**Pull request merged**
