### PR TITLE
Proxy for Webpack.

### PR DESCRIPTION
**Pull request by vssathish**
pull request for https://github.com/coryhouse/react-slingshot/issues/60#event-590595742

### CODE REVIEW

**Comment by coryhouse** [comment]
Thanks for the PR! This is quite clean and straightforward. Only issue I see off-hand is the packages in package.json should be sorted alphabetically.  I need some time to try this myself to understand the implications so please bear with me.

**Comment by raythree** [comment]
This is exactly what I was trying to do. I'm migrating from gulp/browserify to slingshot-based/webpack builds. All of my SPAs talk to backend micro-services, so with gulp/browserify I was generating the output directly into the server/public...so I could do "gulp watch"...edit code, refresh... it was a little slow, but it was managable... the proxy-middleware looks like the perfect solution here.

**Comment by kwelch** [comment]
This solution works well, and I use it in my solutions as well as a proxy file that includes environments and all setup. Is this something that most/all people will need though? Does it make sense to put in more docs on when and why to use it?

**Comment by raythree** [comment]
As most SPAs talk to backend services I think it's very useful, but very site/app specific. I don't think anything is needed from slingshot, except maybe document how to configure it. BTW, I found that http-proxy-middleware was very convenient, especially when there are multiple routes that need to get proxied, and no need to import 'url'. In tools/srcServer:

```javascript
import proxy from 'http-proxy-middleware';

const serverProxy = proxy(['/login', '/api'], {
    target: 'http://localhost:8000',
    changeOrigin: false, // set true for hosted sites
    logLevel: 'debug'
});
// now insert serverProxy into browsersync config into server: { middleware:[.., proxyServer, ...] 
```

**Comment by coryhouse** [comment]
I'd welcome docs on how to use it. Since each person's configuration is going to be unique, it seems docs make more sense than a commit.

**Comment by conoverm** [comment]
thanks to @raythree I got a proxy up. I'm not new to browsersync, but very new to webpack, react, et al. I had no idea where to put the proxy config because I was unsure what was actually serving the app.

Incidentally, http-proxy-middleware is now part of wepback (which served to confuse me a bit further).
https://github.com/webpack/webpack-dev-server/blob/master/package.json#L13

**Comment by kwelch** [comment]
Is this something we want to bundle in with slingshot or is this better suited as a documentation update?

**Comment by coryhouse** [comment]
I lean toward docs since the config will differ by project. A link to this PR and @raythree excellent comment would be a great start.

**Comment by kwelch** [comment]
I currently don't have the availability to write up the documentation for this, but one thing I would recommend, for anyone that is working on features similar to this, to put this type of configuration into a separate file. This will centralize this node server middleware/plugin configuration for both the dev and dist server and ensure consistency. 

I have done this with some of my projects as simply as:
```
import proxy from 'http-proxy-middleware';

module.exports = function (app) {
  app.use(proxy(['/login', '/api'], {
    target: 'http://localhost:8000',
    changeOrigin: false, // set true for hosted sites
    logLevel: 'debug'
  }));
};
```

**Comment by mikedevita** [comment]
Just commenting on my approach on how I handle this along with a .NET backend that uses NTLM and requires the use of agentkeepalive. You could even do like @kwelch suggested and pull the proxy logic out and include it as a middleware all the time it just doesn't do anything if you don't have it enabled. I'm not sure if there is a better way to pull the configs into `package.json` other than from the direct import into `srcServer.js`. Speaking of which has anyone given the thought of pulling these configs out into the base dir either in a `config.js` file or into `package.json`?

I do know that the order of the proxyMiddleware is important, i always put it at the beginning of the browserSync middleware array.

it'd be great if there was a yeoman generator for this slingshot boilerplate that asks you a few questions, like do you need a proxy, whats the endpoints, etc and builds it out for you.

Anyways this is my steps as I have documented:

## install required proxy packages

```shell
yarn add -D http-proxy-middleware agentkeepalive
# -- or --
npm install --save-dev http-proxy-middleware agentkeepalive
```

## In package.json add the following...

```json
   "proxy": {
    "enabled": true,
    "routes": "/api",
    "options": {
      "target": "http://localhost:6741",
      "changeOrigin": false,
      "logLevel": "debug"
    },
    "keepAlive": {
      "enabled": true,
      "options": {
        "maxSockets": "100",
        "keepAlive": true,
        "maxFreeSockets": "10",
        "keepAliveMsecs":"1000",
        "timeout": "60000",
        "keepAliveTimeout": "30000"
      }
    }
  },
```

## in tools/srcServer.js replace with the following

```js
// This file configures the development web server
// which supports hot reloading and synchronized testing.

// Require Browsersync along with webpack and middleware for it
import browserSync from 'browser-sync';
// Required for react-router browserHistory
// see https://github.com/BrowserSync/browser-sync/issues/204#issuecomment-102623643
import historyApiFallback from 'connect-history-api-fallback';
import webpack from 'webpack';
import webpackDevMiddleware from 'webpack-dev-middleware';
import webpackHotMiddleware from 'webpack-hot-middleware';
import config from '../webpack.config.dev';
import proxy from 'http-proxy-middleware';
import Agent from 'agentkeepalive';
import packageJson from '../package.json';

const bundler = webpack(config);
let middleware = [];

if (packageJson.proxy.enabled) {
  let options = packageJson.proxy.options;

  if (packageJson.proxy.keepAlive.enabled) {
    const keepaliveAgent =  new Agent(packageJson.proxy.keepAlive.options);

    const onProxyRes = function (proxyRes, req) {
      const key = 'www-authenticate';
      proxyRes.headers[key] = proxyRes.headers[key] && proxyRes.headers[key].split(',');
    };

    options = {
      ...options,
      agent: keepaliveAgent,
      onProxyRes: onProxyRes
    };
  }
  
  const proxyMiddleware = proxy(
    packageJson.proxy.routes,
    options
  );

  middleware.push(proxyMiddleware);
}

middleware = [
  ...middleware,
  historyApiFallback(),
  webpackDevMiddleware(bundler, {
    // Dev middleware can't access config, so we provide publicPath
    publicPath: config.output.publicPath,
    // These settings suppress noisy webpack output so only errors are displayed to the console.
    noInfo: true,
    quiet: false,
    stats: {
      assets: false,
      colors: true,
      version: false,
      hash: false,
      timings: false,
      chunks: false,
      chunkModules: false
    },

    // for other settings see
    // https://webpack.js.org/guides/development/#using-webpack-dev-middleware
  }),

  // bundler should be the same as above
  webpackHotMiddleware(bundler)
];

// Run Browsersync and use middleware for Hot Module Replacement
browserSync({
  port: 3000,
  open: false,
  ui: {
    port: 3001
  },
  server: {
    baseDir: 'src',
    middleware
  },

  // no need to watch '*.js' here, webpack will take care of it for us,
  // including full page reloads if HMR won't work
  files: [
    'src/*.html'
  ]
});
```

**Comment by nickytonline** [comment]
This PR is quite old, but just following up. From the comments, I think the consensus was to document this instead?

**Comment by kwelch** [comment]
Yes, I agree.

**Comment by nickytonline** [comment]
Closing this and will add to #60 that we just document this.

**Pull request closed without merging**
