### PR TITLE
Add "webpack-dashboard"

### PR DESCRIPTION
**Pull request by BR0kEN-**
### Changes

Use [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard) plugin as standard CLI output for development server.

### CODE REVIEW

**Comment by BR0kEN-** [comment]
@coryhouse, or, maybe makes a sense to add a new command like `npm run dashboard` to run it?

```diff
-    "start": "webpack-dashboard -- npm-run-all --parallel test:watch open:src lint:watch",
+    "start": "npm-run-all --parallel test:watch open:src lint:watch",
+    "dashboard": "webpack-dashboard -- npm start",
```

**Comment by fayimora** [comment]
+1 for dashboard command 😈

**Comment by coryhouse** [comment]
Thanks for the PR! However, this moves all the log output to a tiny window which masks the results of failed tests and linting issues. I can see how this could be useful as a separate script, but I don't see this as a replacement for the existing command line output.

**Comment by BR0kEN-** [comment]
All notes above have sense. Agree with you, guys.

**Comment by coryhouse** [comment]
Thanks @BR0kEN- Change looks great. I'm confused though - it lists the size of react-dom as over 500k! O_o. That's not right. Did you see the same?

**Comment by BR0kEN-** [comment]
No, for me it's normal-sized. Didn't you mixed it up with React?

wdcli

**Comment by coryhouse** [comment]
React-dom is listed as 532K on my machine. 

https://www.dropbox.com/s/18e4q7r1onxpyam/Screenshot%202016-12-20%2004.42.37.png?dl=0

I'm running Node 6.9.2 on Mac.

**Comment by BR0kEN-** [comment]
Maybe something got to that folder accidentally? Try `ls -lh node_modules/react-dom/*`.

wdcli

**Comment by coryhouse** [comment]
Interesting. My sizes are dramatically different: https://www.dropbox.com/s/f25e5bzxjpaatl6/Screenshot%202016-12-20%2005.37.44.png?dl=0

**Comment by fayimora** [comment]
I seem to have the same as @coryhouse

**Comment by BR0kEN-** [comment]
@coryhouse, @fayimora I ran `ls` in an existing configuration, which was built in October.

Now I've made a fresh `npm install` and have the same results. I suppose that ReactDOM was a bit expanded :)

**Comment by BR0kEN-** [comment]
@coryhouse, anyway I'm not guessing that this is a problem of an existing PR. Because the results will not differ, if you revert all changes I've made.

**Comment by coryhouse** [comment]
After thinking on this, I've decided to leave this feature out:
1. It provides a redundant interface that makes it harder to read the important output from linting and testing.
2. The dev build size it provides isn't representative of the production build size, so it's not necessarily actionable.
3. The module data it provides is already available in the analyze-bundle script.
4. It's trivial to add for those who prefer it.

That said, I appreciate the PR! 👍

**Pull request closed without merging**
