### PR TITLE
Better HMR with React Hot Loader v3

### PR DESCRIPTION
**Pull request by paulwithap**
Added React Hot Loader v3 beta to the project for hot reloading components.

### CODE REVIEW

**Comment by kwelch** [comment]
I have been thinking about putting this in. I will give this a run through tonight.

**Comment by coryhouse** [comment]
Thanks for the PR! However, I'd rather not integrate this until it comes out of Beta. Pulling it in now risks bugs and signs us up for an unknown amount of upcoming churn.

**Comment by paulwithap** [comment]
Understandable. The implementation is pretty minimal, so hopefully it's just a matter of bumping the version once 3.0 is released.

**Comment by oshalygin** [comment]
Imo can we have a single commit, it's easier to manage the fork and pick/choose stuff that makes sense.  

Single atomic commits

**Comment by iLeonelPerea** [comment]
Now isn't beta https://www.npmjs.com/package/react-hot-loader

**Comment by coryhouse** [comment]
I'd welcome a pr. :)

**Comment by oshalygin** [comment]
@coryhouse using it now on my fork, i'll submit a PR shortly

**Comment by kwelch** [comment]
I am going to close this in favor of the most recent PR (#392). We appreciate your work on this and look forward to future contributions. 👍

**Pull request closed without merging**
