### PR TITLE
For solving 'Requires Babel "^7.0.0-0", but was loaded with "6.23.3"'

### PR DESCRIPTION
**Pull request by bachnxhedspi**
The error as I described [here](https://github.com/coryhouse/react-slingshot/issues/598) will be solved when updating jest to newer version.

The code review checklist below is used for all pull requests.

 1. Review the list before submitting your pull request.
 2. Leave the list intact for the code reviewer's use.

## Checklist

- [x] Latest code from master has been merged into the pull request branch
- [x] Honors [the seven code virtues](https://pragprog.com/magazines/2011-08/how-virtuous-is-your-code)
  - [x] Working, as opposed to incomplete
  - [x] Unique, as opposed to duplicated
  - [x] Simple, as opposed to complicated
  - [x] Clear, as opposed to puzzling
  - [x] Easy, as opposed to difficult
  - [x] Developed, as opposed to primitive
  - [x] Brief, as opposed to chatty
- [x] Code is camelCased
- [x] No commented out code (if required, place // TODO above with explanation)
- [x] No linting issues
- [x] Automated tests exist and pass
- [x] Build is successful (`npm run build`)
- [x] Works in IE 11, Chrome, Firefox, and Edge

## Thanks!

:heart:

### CODE REVIEW

**Comment by nickytonline** [comment]
Just following up on this PR. Looks like it's failing for node 9, https://ci.appveyor.com/project/CoryHouse/react-slingshot/builds/22616792/job/mc1m4pwp9cffdwu7

**Comment by ajwest** [comment]
I ran into this problem on Node 12.  Upgrading `jest`, `jest-cli` and `babel-jest` to `^24.8.0` inside `package.json` has fixed it for me.

**Comment by nickytonline** [comment]
@ajwest, we dropped node 9 support, so there's that. 😉

**Comment by nickytonline** [comment]
Is this good to go then @coryhouse?

**Comment by kwelch** [comment]
There are no file changes outside of removal of lock file. Do we still need this?

**Comment by coryhouse** [comment]
Agreed Kyle. This can be closed.

**Pull request closed without merging**
