### PR TITLE
Info and links on how to configure output.publicPath for deployment

### PR DESCRIPTION
**Pull request by IlyaMurashov**
Thanks everyone for maintaining this awesome repo!
Here's my two cents :)

### CODE REVIEW

**Comment by IlyaMurashov** [comment]
Thanks everyone for maintaining this awesome repo!
Here's my two cents :)

**Comment by coryhouse** [comment]
Thanks! What does NB stand for? Can you please remove it?

**Comment by IlyaMurashov** [comment]
@coryhouse done! It stood for nota bene ;)

**Comment by coryhouse** [comment]
Thanks so much!

**Pull request merged**
