### PR TITLE
Update to react hot loader

### LINKED ISSUE #554: Deprecated dependency - react-transform-hmr
Hi,
I have noticed that the package used in the project `babel-preset-react-hmre` is using [react-transform-hrm](https://github.com/gaearon/react-transform-hmr) which according to the README of the project has been deprecated in favour of [react-hot-reloader](https://github.com/gaearon/react-hot-loader)
Should the dependency be updated ?

### PR DESCRIPTION
**Pull request by Maxim-Filimonov**
Resolves #554

### CODE REVIEW

**Comment by Maxim-Filimonov** [comment]
@coryhouse is it good or ?

**Comment by coryhouse** [comment]
Sorry, this PR fails on my Mac: 

2018-04-10 08:59 node[39064] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
✓ Clean (08:59:19)

2018-04-10 08:59 node[39064] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1351:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slingshot@7.0.1 test:watch: `jest --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@7.0.1 test:watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/coryhouse/.npm/_logs/2018-04-10T13_59_19_722Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slingshot@7.0.1 start: `concurrently -k -r -s first "npm run test:watch" "npm run open:src" "npm run lint:watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@7.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/coryhouse/.npm/_logs/2018-04-10T13_59_19_897Z-debug.log

**Comment by Maxim-Filimonov** [comment]
Eh. it passes on travis.. 😕

**Comment by Maxim-Filimonov** [comment]
@coryhouse have you tried updating your watchman?

**Comment by coryhouse** [comment]
Turned out it was just an issue with Node on my machine. Works great now. Thanks so much! 👍

**Pull request merged**
