### PR TITLE
Use single quote in .woff loader value string

### PR DESCRIPTION
**Pull request by yoniji**

### CODE REVIEW

**Comment by coryhouse** [comment]
Closing since duplicate

**Comment by kwelch** [comment]
This is not a dup it was two different files. Other PR was for `webpack.dev.config` this is for `webpack.prod.config`

**Comment by kwelch** [comment]
Thanks for merging, not sure why but I was waiting for builds to complete.

**Comment by coryhouse** [comment]
Thanks for the heads up @kylewelch! 

And thanks @yoniji!

**Pull request merged**
