### PR TITLE
Added the webpack bundle analyzer.

### PR DESCRIPTION
**Pull request by nickytonline**
Implements #295

### CODE REVIEW

**Comment by nickytonline** [comment]
When you run `npm start`, everything runs like normal, but another browser tab will open at http://localhost:8888, which will show the bundle analyzer results.

**Comment by coryhouse** [comment]
Great add! 👍 

I've really appreciated your contributions Nick. Just sent ya an invite to be a contributor with @kwelch and I. No pressure, but would love to have you on the team. :)

**Comment by nickytonline** [comment]
@coryhouse, thanks for the invite! Just accepted it.

**Comment by coryhouse** [comment]
Woot! Glad to have you on board! :)

**Comment by coryhouse** [comment]
Do you know if there's a way to trace a given file listed in the bundle analyzer back to the place it was imported?

**Comment by nickytonline** [comment]
Off hand no, but I'll read up/dig a bit to see if its possible.

**Comment by kwelch** [comment]
Congratulations @nickytonline, well deserved.

**Pull request merged**
