### PR TITLE
Added ability to test components with imported styles and do cheerio assertions

### PR DESCRIPTION
**Pull request by jeremyadavis**
Enhanced testability a bit by adding the following:
- Added [ignore-styles](https://www.npmjs.com/package/ignore-styles) to allow mocha to test components with imported css/scss.
- Added [chai-cheerio](https://github.com/Merott/chai-cheerio) to do cheerio assertions.

### CODE REVIEW

**Comment by coryhouse** [comment]
Hi Jeremy. Thanks for the PR! Can you do me a favor and split this into two since it's two unrelated changes? I definitely want to accept the ignore-styles change, but need to look into chai-cheerio more. Hesitant to add since it is so young.

**Comment by jeremyadavis** [comment]
Sure thing.

I'll do the ignore-styles today.

I plan on writing unit tests for around 15 components built on slingshot this week, so I'll put chai-cheerio through the ringer a bit and submit a PR for it if I don't have any problems.

**Comment by coryhouse** [comment]
Awesome! I've been meaning to improve test coverage so I'm excited to see your work!

**Comment by coryhouse** [comment]
Closing since handling via separate PRs

**Comment by coryhouse** [comment]
@jeremyadavis Just FYI - Found a way to resolve this for all Webpack-specific features today, so I committed a change. https://github.com/coryhouse/react-slingshot/issues/102

**Pull request closed without merging**
