### PR TITLE
updates to travis ci config for yarn.

### PR DESCRIPTION
**Pull request by nickytonline**
Not ready to merge yet, just testing if CI runs properly. This implements enhancement #323

### CODE REVIEW

**Comment by nickytonline** [comment]
The change to the configuration works, but since we don't add an install directive, the default is run which runs

`yarn` and `npm test` which is not what we want because we have an after success step that runs coveralls and runs the tests. As they state on their [blog post](https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn), "Please note that, at this time, Yarn is not yet pre-installed on our build images. This means that, if yarn.lock does not exist in the expected location, you are responsible for installing Yarn yourself."

Let's wait to merge this once it's pre-installed so we can just run 'yarn' at the install phase.

**Comment by coryhouse** [comment]
Cool, and agreed. 👍

**Comment by cyprusglobe** [comment]
@nickytonline @coryhouse might take a look now looks like its preinstalled for trusty according to this https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/

**Comment by nickytonline** [comment]
Thanks @cyprusglobe. I'll test it out.

**Comment by nickytonline** [comment]
@coryhouse, this is good to merge now.

**Comment by coryhouse** [comment]
Thanks Nick! 👍

**Pull request merged**
