### PR TITLE
Update package.json

### LINKED ISSUE #449: Start script fails after initial installation.
Node version:
v8.1.4

npm version:
5.0.3

Operating system:
macOS Sierra v10.12.5

Command line used:
iTerm2

Steps to reproduce:
* (For issue 1)
1.) `npm run setup` or `npm install`
2.) `npm start -s` or `npm start`

* (For issue 2)
After issue 1 is resolved, run
`npm start -s` or `npm start`

Issue 1:
After initial installation via `npm run setup` or `npm install`, start script fails. Error output provided below.

Error Output:
```
2017-07-18 00:01 node[20270] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-07-18 00:01 node[20270] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1360:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slingshot@7.0.0 test: `jest "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@7.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/branden/.npm/_logs/2017-07-18T04_01_38_701Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slingshot@7.0.0 test:watch: `npm run test -- --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@7.0.0 test:watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/branden/.npm/_logs/2017-07-18T04_01_38_725Z-debug.log
ERROR: "test:watch" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slingshot@7.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@7.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/branden/.npm/_logs/2017-07-18T04_01_38_821Z-debug.log
```

Issue 2:
After fixing issue 1 (see above), start script fails. Error output provided below.

Error Output:
```
 RUNS  src/components/FuelSavingsForm.spec.js
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.22:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.22:3001
 -------------------------------------
[BS] Serving files from: src
[BS] Watching files...
can't resolve reference #/definitions/basicConfig from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
 PASS  src/components/FuelSavingsForm.spec.jsnfigOrBoolean from id #
 PASS  src/components/FuelSavingsResults.spec.js
 PASS  src/store/store.spec.js
 PASS  src/reducers/fuelSavingsReducer.spec.js
 PASS  src/utils/fuelSavingsCalculator.spec.js
 PASS  src/actions/fuelSavingsActions.spec.js
 PASS  src/utils/mathHelper.spec.js
 PASS  src/components/AboutPage.spec.js

 PASS  src/components/FuelSavingsTextInput.spec.js

 RUNS  src/containers/FuelSavingsPage.spec.js
/Users/branden/Documents/GitHub/react-slingshot/tools/setup/setupPrompts.js (1/0)
  ✖  6:28  Unnecessary escape character: \.  no-useless-escape

✖ 1 error (12:05:24 AM)


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slingshot@7.0.0 lint: `esw webpack.config.* src tools --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@7.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/branden/.npm/_logs/2017-07-18T04_05_24_348Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slingshot@7.0.0 lint:watch: `npm run lint --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@7.0.0 lint:watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/branden/.npm/_logs/2017-07-18T04_05_24_377Z-debug.log
ERROR: "lint:watch" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slingshot@7.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@7.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/branden/.npm/_logs/2017-07-18T04_05_24_482Z-debug.log
```

### PR DESCRIPTION
**Pull request by techmexdev**
Fixes #449

### CODE REVIEW

**Comment by coryhouse** [comment]
I've never seen a third set of dashes used before. Have a link that explains how this works? Also unclear how this solves #449.

**Comment by nickytonline** [comment]
I've never seen the triple double dash used either.

**Comment by techmexdev** [comment]
Seems to be "passing" `-- --watch`into `npm test`. Which then passes `--watch`. https://facebook.github.io/jest/docs/en/cli.html#using-with-npm-scripts.

**Comment by techmexdev** [comment]
#497 also fixes the issue, but is perhaps more clear.

**Comment by coryhouse** [comment]
Cool, I prefer #497.

**Comment by kwelch** [comment]
I actually have had to use the extra set of dashes, it has to match the depth of nesting.

**Comment by coryhouse** [comment]
Well whatta ya know, learned my new thing for the day. :)

I still prefer 497. Agreed?

**Comment by techmexdev** [comment]
Agreed 👍

**Comment by nickytonline** [comment]
I'm fine either way, so unless @kwelch is not a fan of #497, we can go ahead with #497.

**Comment by kwelch** [comment]
Moved forward with #497 👍 Thanks, good work

**Pull request closed without merging**
