### PR TITLE
Make bundle URL relative to index.html

### PR DESCRIPTION
**Pull request by firstdoit**
This allows a deploy to non-root URLs to be seamless.

### CODE REVIEW

**Comment by coryhouse** [comment]
I added the leading slash to [resolve this](https://github.com/coryhouse/react-slingshot/issues/65). That said, he never shared if that helped. If we can confirm that nested routes can reload successfully during dev without the leading slash then I can accept this PR.

Thanks!

**Comment by rndstr** [comment]
I think `bundle.js` can be either absolute or relative but it must be the same as `styles.css` in tools/buildHtml.js which it is currently not. Otherwise it can break in production.

For me it needs to be absolute since I have entry points that are on the second level (app at example.com and client can come in at example.com/en/something). And even if you have your app at a sub path like example.com/calculator/, if you want to support clients loading your app from example.com/calculator/en/something you will need to make it absolute with the current setup.

I opened a PR to fix the current state (`styles.css` being not the same as `bundle.js`) but feel free to close if you would rather have both relative.

**Comment by coryhouse** [comment]
@firstdoit Can I close this? Does #143 resolve this for you?

**Comment by firstdoit** [comment]
Not sure if everything absolute is what most people expect (or even how it solves the problem of deploying to multi-level paths, given that now we're restricted to root!), but sure, any decision is better than no decision!

**Comment by rndstr** [comment]
@firstdoit I see what you mean

Relative solves the problem of deploying to multi-level paths. Absolute solves the problem of reloading an app after navigating to a multi-level path.

But, I think react-slingshot does at the current state not support reloading the site after navigating, correct me if I'm wrong. Which would make my point moot for having it absolute. If you do have navigation&reload support (which my application has) then I think it is inevitable to have it absolute.

**Comment by firstdoit** [comment]
AFAIK the expected behaviour in a React (or rather any SPA) app is to have the app itself handle all navigation and routing. I agree that for anything non-trivial, specially using `History`, you'll eventually have to bolt down the paths. In this case, however, I'd either document this detail or make it simple to add a `base path`

**Pull request closed without merging**
