### PR TITLE
Order babel presets so they work correctly

### LINKED ISSUE #485: Integrate class-properties-transform for Babel?
FEATURE REQUEST.

I'd like to see the class-properties-transform to be integrated by default into react-slingshot, so people can benefit from the new, less boilerplate-y syntax.

Here's more on this: https://babeljs.io/docs/plugins/transform-class-properties/

Are PRs accepted on very much needed improvements like this?

### PR DESCRIPTION
**Pull request by samit4me**
Fixes #485

### CODE REVIEW

**Comment by kwelch** [comment]
Is it possible to centralize them and get the proper order?

**Comment by samit4me** [comment]
Yes I know what you mean, it doesn't look great. I don't know of any other way but that doesn't mean you can't. Will have another look when I get some more time.

**Comment by coryhouse** [comment]
I agree centralizing would be preferable if possible, but this reads clearly as is, so I'm good w/ merging as is if @kwelch and @nickytonline are.

**Comment by nickytonline** [comment]
I'm fine with it as is. 👍

**Comment by kwelch** [comment]
I pulled this locally to try it out and got runtime errors with the production build. 

```Uncaught Error: Module build failed: Error: Unexpected extra options ["react","stage-1"] passed to preset.```

**Comment by kwelch** [comment]
Validated by changing SavingsForm to use arrow functions and static propTypes.

**Comment by kwelch** [comment]
AppVeyor died for a peerDep, but I don't see any issues with merging.

**Comment by samit4me** [comment]
Great pickup @kwelch, thank you for finding that issue ✨

**Pull request merged**
