### PR TITLE
Added blurb about how to debug in VS Code.

### PR DESCRIPTION
**Pull request by nickytonline**
@coryhouse, @kwelch, I've updated the README.md to explain the steps on how to debug in VS Code. Just give it a quick read to let me know if it sounds OK.

### CODE REVIEW

**Comment by nickytonline** [comment]
This fixes #259.

**Comment by coryhouse** [comment]
Great. Suggest moving this blurb to the FAQ instead of the main page. Also suggest dropping the last bullet about issues for brevity. (Goal is to have a clean front page with only the critical info).

I also want to organize the FAQ with anchors at the top since it's gotten long, but that's a separate to do for another day.

**Comment by nickytonline** [comment]
OK, thanks for the feedback. I'll make the change.

**Comment by nickytonline** [comment]
@coryhouse, I've moved it to the FAQ.md with your suggestions.

**Comment by coryhouse** [comment]
Thanks Nick!

**Pull request merged**
