### PR TITLE
update setup script

### LINKED ISSUE #417: Update the setup script
#### Expected behavior:
If user submits an empty string, or something else then "y/n", git should be removed. ( Can be changed to `y/N` )
#### Actual behavior: 
If user submits anything else than `y/yes` git isn't removed.

#### Expected behavior:
If user choose to not delete git, he still able to update `package.json` file
#### Actual behavior: 
If user chose to not delete git, setup script ends. 

#### Expected behavior:
After setup ends, setup files and script are deleted from project.
#### Current behavior:
Only setup files are deleted, `setup` script remains in `package.json`, but script are broken, because of missing files.

### PR DESCRIPTION
**Pull request by RoM4iK**
fixes #417

### CODE REVIEW

**Comment by nickytonline** [comment]
Hi @RoM4iK, thanks for the PR! Can you create an issue explaining the need for the change? It helps us keep track of changes to the repo and allows for discussion of the issue. Thanks.

**Comment by nickytonline** [comment]
And link the issue to the PR. Cheers.

**Comment by RoM4iK** [comment]
cc @nickytonline

**Comment by coryhouse** [comment]
Looks great - Thanks for the PR! 👍

**Pull request merged**
