### PR TITLE
Remove less support due to #526

### PR DESCRIPTION
**Pull request by leonimurilo**
Remove less support as an alternative to issue #526

### CODE REVIEW

**Comment by coryhouse** [comment]
Looks good. @sag1v - This rolls back your less add since it caused a regression. Would welcome a PR from you as an alternative to removing the less support. Suggestion: Need to declare Less loader separately from Sass so the same loaders don't apply to both.

**Comment by sag1v** [comment]
@coryhouse  fair enough.
@kwelch [i guess the ordering does matter](https://github.com/coryhouse/react-slingshot/pull/512#pullrequestreview-82548827) 😞

**Comment by nickytonline** [comment]
Everything looks good, when comparing it to the addition of LESS in #512.

**Comment by coryhouse** [comment]
Merged. Thanks for reporting!

**Pull request merged**
