### PR TITLE
Add CONTRIBUTE.md

### PR DESCRIPTION
**Pull request by coryhouse**

### CODE REVIEW

**Comment by nickytonline** [comment]
Looks like there's trouble with `yarn` on Travis. I'll take a peek to see what's up.

**Comment by kwelch** [comment]
LGTM

**Comment by nickytonline** [comment]
LGTM too, just curious about Travis failing. I'll try to look at it tonight.

**Comment by kwelch** [comment]
Looks to be related to #412, I cannot run yarn locally.

**Comment by nickytonline** [comment]
Weird, I was able to install locally last week. I'll reopen #412. We're OK
to merge this @coryhouse.

**Comment by kwelch** [comment]
I was able to fix the build with a `yarn upgrade` it updated the yarn lock and all appears to be good.

**Comment by kwelch** [comment]
I am going to move my yarn.lock update into master that way it is not part of this change.

**Comment by nickytonline** [comment]
@coryhouse, can you rebase? I'll merge after that's done. I'll also update the issue template in another PR to mention to read the contributing.md unless you want to add it yourself in this PR.

**Comment by kwelch** [comment]
One thing @kentcdodds added to glamorous recently was a checklist to the PR template. 

I really like that idea, we should follow suit. 

Here is a link to a PR that uses it:
https://github.com/paypal/glamorous/pull/117#issue-230045188

**Comment by kentcdodds** [comment]
For what it's worth, most projects I've seen call this file `CONTRIBUTING.md` rather than `CONTRIBUTE.md`

**Comment by nickytonline** [comment]
That's my bad. Thanks for the correction @kentcdodds. @coryhouse, can you rename the file in your PR along with the rebase?

**Pull request merged**
