### PR TITLE
Add express to serve static files

### LINKED ISSUE #427: Add express to serve static files

### PR DESCRIPTION
**Pull request by iLeonelPerea**
closes #427 

Changes proposed in the pull request:

- Add express for production
- Update favicon

@coryhouse

### CODE REVIEW

**Comment by kwelch** [comment]
Could you provide the 'why' for this change? What does this give us?

**Comment by iLeonelPerea** [comment]
@kwelch

The actual configuration uses browsersync, isn't intended for production, to serve static files and i propose to use express. Because the actual configuration of browsersync share the same sesion if you access from multiple web browsers. 

Maybe some developers try to use the same configuration for production that does not work with browsersync.. 

But I got your point..

**Comment by ryannealmes** [comment]
Surely where the files from production get served is separate from this repo? For example I build react-slingshot and store my files in an S3 bucket and serve it from there. Express wouldn't really serve any purpose.

**Comment by kwelch** [comment]
Yes, the intent of the distServer is to validate the production code. Its purpose was not to be a production ready server. This may server better as part of the documentation we are looking to compile for #408

**Pull request closed without merging**
