### PR TITLE
Fix Jest issue on Node 7.

### PR DESCRIPTION
**Pull request by coryhouse**
Eliminating the harmony-proxies reference on the plain test script since (I think) it's only needed for Travis.

### CODE REVIEW

**Comment by kwelch** [comment]
You will probably need to update the `.travis.yml`, it is currently using the default of `npm test`

Also, should we be testing that it builds? Current script is not doing this.

**Comment by coryhouse** [comment]
Good point. How'd the never occur to me?!

**Comment by kwelch** [comment]
Don't forget about appveyour. Also may want to have a custom `build:ci`, that uses `test:travis` and does not open the dist-server.

**Comment by coryhouse** [comment]
Merging since this fixes the Node 7 issue for those running locally. Node 7 on Travis and Appveyor are failing [due to this issue](https://github.com/adonisjs/adonis-framework/issues/357), but that only effects CI. Will figure out how to fix the CI in a separate ticket.

**Pull request merged**
