### PR TITLE
Update dependencies to fix audit and peer dependencies

### PR DESCRIPTION
**Pull request by kwelch**
# Pull Request Template

Note: There is still one audit error and it is related to `tar` which is a deep dependency (`node-sass > node-gyp > tar`), more details here (https://nodesecurity.io/advisories/803)

The code review checklist below is used for all pull requests.

 1. Review the list before submitting your pull request.
 2. Leave the list intact for the code reviewer's use.

## Checklist

- [x] Latest code from master has been merged into the pull request branch
- [x] Honors [the seven code virtues](https://pragprog.com/magazines/2011-08/how-virtuous-is-your-code)
  - [x] Working, as opposed to incomplete
  - [x] Unique, as opposed to duplicated
  - [x] Simple, as opposed to complicated
  - [x] Clear, as opposed to puzzling
  - [x] Easy, as opposed to difficult
  - [x] Developed, as opposed to primitive
  - [x] Brief, as opposed to chatty
- [x] Code is camelCased
- [x] No commented out code (if required, place // TODO above with explanation)
- [x] No linting issues
- [x] Automated tests exist and pass
- [x] Build is successful (`npm run build`)
- [x] Works in IE 11, Chrome, Firefox, and Edge

## Thanks!

:heart:

### CODE REVIEW

**Comment by nickytonline** [comment]
Oops. Looks like CI is failing at the moment.

**Comment by kwelch** [comment]
Looks like there is a package in there that does not like node 9.

**Comment by kwelch** [comment]
I am not sure it is possible to make it happy since it has it engines set to:
`"6.* || 8.* || >= 10.*"`

On a related note, we have `engines` defined and the node check script. Do we need the script if we have the engine in place?

**Comment by nickytonline** [comment]
Probably not. On mobile BBQing so not currently set up to dig deep.
1F344893-9F16-4090-AD20-B266674070FC

**Comment by coryhouse** [comment]
[Node 9 isn't supported by Node](https://github.com/nodejs/Release), so I'm removing from our CI.

Thanks guys!

**Pull request merged**
