### PR TITLE
Lock the node version to 8.

### PR DESCRIPTION
**Pull request by coryhouse**
Found a handy trick that should help enforce consistency: https://twitter.com/housecor/status/962347301456015360

Look good @nickytonline @kwelch ?

### CODE REVIEW

**Comment by coryhouse** [comment]
Ah, good point on dev dep. Given that Node is only for dev purposes here, that is the better choice.

The bigger problem: Appveyor ain't happy about this change because it appears the specified version isn't available on their platform. 🤔

**Comment by nickytonline** [comment]
That's odd that they don't have it given that Node 8.9.x is the current LTS. I'm totally OK with going all in on Node 8 as it's only for building the front-end. I can't think of any negatives.

**Comment by coryhouse** [comment]
I've opened an issue with Appveyor.

**Comment by nickytonline** [comment]
So looks like we're good to go as soon as the AppVeyor issue is sorted out.

**Comment by nickytonline** [comment]
Looks like you got AppVeyor sorted out @coryhouse. 👍

**Comment by nickytonline** [comment]
Nevermind. My eyes were deceiving me. It's just Coveralls.

**Comment by kwelch** [comment]
Why are we dropping lock files?

**Comment by coryhouse** [comment]
Just added the lock files back. Finally got the CI quirks resolved so we should be good now.

**Comment by kwelch** [comment]
Awesome. Excited to have this locked in! Nice work

**Pull request merged**
