### PR TITLE
Rename businessLogic to utils

### PR DESCRIPTION
**Pull request by zsherman**
Maybe it's a personal preference, but I feel like `utils` is a better standard here.

### CODE REVIEW

**Comment by coryhouse** [comment]
Hi @zsherman. I chose the name "businessLogic" to convey that it contains logic that isn't tied to React or specific to any front-end library. In my front-end apps, I strive to extract my logic into separate "POJOs" when possible so that it can be easily testing in isolation. I was seeking to convey a "business logic layer" on the client. I'm not sure that "utils" conveys that mission as clearly. 

Given this description, does that change your thoughts on the naming? 

I'm going to let this sit for a bit since I'd love to hear from others on their opinion.

**Comment by zsherman** [comment]
I see what your saying – I don't have a really strong opinion here, the naming just felt a little unconventional compared to "lib" or "utils" or something along those lines.

**Comment by tsongas** [comment]
I agree businessLogic feels icky. Maybe "core" would work?

**Comment by jondot** [comment]
I think 'helpers' is what you guys are looking for.

**Comment by coryhouse** [comment]
Related poll: https://twitter.com/housecor/status/745962536751632385

**Comment by coryhouse** [comment]
@zsherman Thanks for the PR - I just committed this change. Your suggestion of utils ended up being the most popular in the Twitter poll I posted. Thanks everyone for the input!

**Comment by zsherman** [comment]
👍

**Pull request closed without merging**
