### PR TITLE
Babel-6 Upgrade + All Dependencies Update - Local Test OK

### PR DESCRIPTION
**Pull request by Bartekus**
Thank you for making this very well throughout boilerplate Cory!

I'm a big fan of your work and you have not disappointed me with this one gem either, one of the best react boilerplates I've seen, and I track them all like a hound! Good job!

So this is small adjustment but it will bring all dependencies up to date along with babel-6 configured as per previous config (except that stage-2 became stage-1 with babel 6 update).

### CODE REVIEW

**Comment by coryhouse** [comment]
Wow, thanks so much for the PR! I've been holding off on upgrading to Babel 6 until all related dependencies have been updated accordingly. I'm going to let this sit for a few days to see if babel-eslint 5 is released. To help assure stability, I'd like to avoid taking dependencies on beta versions.

**Comment by barrystaes** [comment]
:+1: Nice!

**Comment by coryhouse** [comment]
@Bartekus Thanks so much for this PR! Made it super easy to upgrade now that babel-eslint 5.0.0 is out. Just merged in.

**Comment by Bartekus** [comment]
Not a problem Cory, I'm glad I could help! Thank you for teaching, I've learn a lot and still learn so much everyday thanks to great teachers like yourself! Keep on, keeping on my friend!

**Comment by halayli** [comment]
I suggest you also add "babel-plugin-transform-react-inline-elements" to babel's transforms.

**Comment by coryhouse** [comment]
@halayli - Thanks for the recommendation. I'm considering it, but would like to track it in a separate issue.

@Bartekus - Thanks for the kind words! :)

**Pull request closed without merging**
