### PR TITLE
Markdown docs lint and cleanup

### PR DESCRIPTION
**Pull request by ivannieto**
The code review checklist below is used for all pull requests.

 1. Review the list before submitting your pull request.
 2. Leave the list intact for the code reviewer's use.

Thanks! :)

## Code Review Checklist

- [x] Latest code from master has been merged into the pull request branch
- [x] Honors [the seven code virtues](https://pragprog.com/magazines/2011-08/how-virtuous-is-your-code)
  - [x] Working, as opposed to incomplete
  - [x] Unique, as opposed to duplicated
  - [x] Simple, as opposed to complicated
  - [x] Clear, as opposed to puzzling
  - [x] Easy, as opposed to difficult
  - [x] Developed, as opposed to primitive
  - [x] Brief, as opposed to chatty
- [x] Code is camelCased
- [x] No commented out code (if required, place // TODO above with explanation)
- [x] No linting issues
- [x] Automated tests exist and pass
- [x] Build is successful (`npm run build`)
- [x] Works in IE 11, Chrome, Firefox, and Edge

---

This PR aims to improve clarity on reading and maintaining markdown docs.

### CODE REVIEW

**Comment by coryhouse** [comment]
Thanks for the PR! I see you removed the anchor tags above the headings in the README. Are you saying the links will continue to work without those?

**Comment by ivannieto** [comment]
@coryhouse they do, all the headings are rendered as slugs removing special characters, for example:

 ## What The Heading?

gets converted into *what-the-heading* and acts as anchor id for all the document or link

all links in the PR are tested, and working as they should

:slightly_smiling_face:

**Comment by coryhouse** [comment]
Thanks again! 👍

**Comment by kwelch** [comment]
This is great! Nice work

**Comment by ivannieto** [comment]
Thanks guys!

**Pull request merged**
