### PR TITLE
Update non-pure components to pure components

### PR DESCRIPTION
**Pull request by nickytonline**
@coryhouse this resolves issue #23.

### CODE REVIEW

**Comment by coryhouse** [comment]
Thanks for the PR Nick! I'm on holiday today but will give this a look tomorrow!

**Comment by coryhouse** [comment]
@nickytonline Okay, you've taught me something. :+1:  I've never seen this pattern of using builder functions so that you can create a stateless functional component. Do you have a link to share where you saw this documented/used?

**Comment by nickytonline** [comment]
@coryhouse it's not React related just JavaScript in general. Functions can return anything including functions, i.e. higher-order functions. I just happened to call them buildFunctionX(props). I opted for this way instead of putting them inline in the pure component as I thought it was more readable but either way can be used.

```
function buildFuelSavingsKeypress(props) {
  return function fuelSavingsKeypress(name, value) {
    props.actions.calculateFuelSavings(props, name, value);
  };
}

…

const FuelSavingsCalculatorForm = (props) => {
  const fuelSavingsKeypress = buildFuelSavingsKeypress(props);
  …
}	
```

or 

```
const FuelSavingsCalculatorForm = (props) => {
  function fuelSavingsKeypress(name, value) {
    props.actions.calculateFuelSavings(props, name, value);
  }

  ...
}	
```

**Comment by coryhouse** [comment]
Right, that's what threw me. I've never seen the builderX pattern. I prefer nesting the function declarations - less boilerplate since you don't have to create the wrapper and call the wrapper. I'm refactoring your PR in that direction. Hope you don't mind. You had a great point - these might as well be stateless functional components!

**Comment by nickytonline** [comment]
@coryhouse no worries... cool beans. I just thought it made sense to have them all as stateless components. Thanks again for the great project. :star:

**Pull request merged**
