### PR TITLE
Updated badges

### PR DESCRIPTION
**Pull request by jasonnathan**
Build status was not accurate and updated all to use shields.io

### CODE REVIEW

**Comment by coryhouse** [comment]
Thanks Jason! 👍

**Comment by kwelch** [comment]
Question: Is it possible to have the badges dynamic based on the branch the user is looking at? Just wondering since this is hardcoded to master.

**Comment by jasonnathan** [comment]
Sure, you'd just have to update the Readme.md per branch. Pull request? :P

**Comment by kwelch** [comment]
I don't think that is necessary, wasn't sure if there was a variable that could be used in place of master to do it "auto-magically"

**Pull request merged**
